name: python unit tests
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pytest-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: torch install
        run: |
          pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cu121

      - name: pytest install
        run: |
          pip install pytest

      - name: _tmp
        run: |
          pip list
